basePath: /
definitions:
  github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError:
    properties:
      code:
        type: string
      message: {}
      status:
        type: integer
    required:
    - code
    - message
    - status
    type: object
  github_com_guemidiborhane_factorydigitale_tech_pkg_movies_models.Favourite:
    properties:
      id:
        type: integer
      movie_id:
        type: integer
      user_id:
        type: integer
    required:
    - id
    - movie_id
    - user_id
    type: object
  github_com_guemidiborhane_factorydigitale_tech_pkg_movies_models.Movie:
    properties:
      genres:
        items:
          type: string
        type: array
      id:
        type: integer
      in_favourites:
        type: boolean
      overview:
        type: string
      poster:
        type: string
      release_date:
        type: integer
      title:
        type: string
    required:
    - genres
    - id
    - in_favourites
    - overview
    - poster
    - release_date
    - title
    type: object
  github_com_guemidiborhane_factorydigitale_tech_pkg_users_auth.UserResponse:
    properties:
      id:
        type: integer
      role:
        type: string
      username:
        type: string
    required:
    - id
    - role
    - username
    type: object
  github_com_guemidiborhane_factorydigitale_tech_pkg_users_auth.UserTracks:
    properties:
      ips:
        items:
          items:
            type: string
          type: array
        type: array
      login_count:
        type: integer
    type: object
  pkg_movies.FavouriteRequestParams:
    properties:
      movie_id:
        type: integer
    type: object
  pkg_permissions.PermissionsParams:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
  pkg_permissions.PermissionsResponse:
    properties:
      permissions:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      roles_permissions:
        $ref: '#/definitions/pkg_permissions.RolesPermissionsMap'
    required:
    - permissions
    - roles_permissions
    type: object
  pkg_permissions.RolesPermissionsMap:
    additionalProperties:
      additionalProperties:
        items:
          type: string
        type: array
      type: object
    type: object
  pkg_users.UserJSONResponse:
    properties:
      permissions:
        items:
          type: string
        type: array
      tracks:
        $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_pkg_users_auth.UserTracks'
      user:
        $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_pkg_users_auth.UserResponse'
    required:
    - permissions
    - tracks
    - user
    type: object
  pkg_users.UserRegisterParams:
    properties:
      password:
        minLength: 6
        type: string
      username:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  pkg_users_auth.LoginParams:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  pkg_users_auth.UserResponse:
    properties:
      id:
        type: integer
      role:
        type: string
      username:
        type: string
    required:
    - id
    - role
    - username
    type: object
info:
  contact:
    email: guemidiborhane@gmail.com
    name: API
  description: Interview
  title: FactoryDigitale
  version: "1.0"
paths:
  /api/auth:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Logout user
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: LoginRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pkg_users_auth.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_users_auth.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Login user
      tags:
      - Users
  /api/movies:
    get:
      parameters:
      - description: offset for paging
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_pkg_movies_models.Movie'
            type: array
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Index Movies
      tags:
      - Movie
  /api/movies/favourite:
    post:
      parameters:
      - description: Favourite Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pkg_movies.FavouriteRequestParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_pkg_movies_models.Favourite'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Toggle movie to/from your Favourites
      tags:
      - Movie
  /api/movies/favourites:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_pkg_movies_models.Movie'
            type: array
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Index Favourites
      tags:
      - Movie
  /api/permissions:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_permissions.PermissionsResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Index Permissions
      tags:
      - Permissions
  /api/permissions/{role}:
    post:
      consumes:
      - application/json
      parameters:
      - description: RoleDefinition
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pkg_permissions.PermissionsParams'
      - description: Role
        in: path
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Store Role
      tags:
      - Permissions
    put:
      consumes:
      - application/json
      parameters:
      - description: RoleDefinition
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pkg_permissions.PermissionsParams'
      - description: Role
        in: path
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Store Role
      tags:
      - Permissions
  /api/user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_users.UserJSONResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Show User
      tags:
      - Users
  /api/user/check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "401":
          description: Unauthorized
          schema:
            type: boolean
      summary: Check
      tags:
      - Users
  /api/users:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pkg_users.UserRegisterParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_pkg_users_auth.UserResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_guemidiborhane_factorydigitale_tech_internal_errors.HttpError'
      summary: Register User
      tags:
      - Users
swagger: "2.0"
